=== xjrga/looks/src/main/resources/palette.xsd
<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="palette">
        <xsd:annotation>
            <xsd:documentation>
                Data Exchange Document Schema For Palette Viewer Software
                Palette Viewer: Software to Create Color Palettes.
                Author: Jorge Garcia R de Alba
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="color" type="color_type" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="Uniquely_Specified_Color">
            <xsd:selector xpath="color"/>
            <xsd:field xpath="red"/>
            <xsd:field xpath="green"/>
            <xsd:field xpath="blue"/>
        </xsd:unique>
    </xsd:element>
    <!-- Color -->
    <xsd:complexType name="color_type">
        <xsd:sequence>
            <xsd:element name="hexcode" type="hex_color_code_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="red" type="red_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="green" type="green_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="blue" type="blue_type" minOccurs="1" maxOccurs="1"/>            
        </xsd:sequence>
    </xsd:complexType>
    <!-- Hex Color Code -->
    <xsd:simpleType name="hex_color_code_type">
        <xsd:restriction base="xsd:hexBinary">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Red -->
    <xsd:simpleType name="red_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Green -->
    <xsd:simpleType name="green_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Blue -->
    <xsd:simpleType name="blue_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== xjrga/looks/palettes/landscape_03.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/palette.xsd">
<name>landscape_03</name>
<color>
<red>94</red>
<green>132</green>
<blue>10</blue>
<hexcode>5e840a</hexcode>
</color>
<color>
<red>249</red>
<green>221</green>
<blue>217</blue>
<hexcode>f9ddd9</hexcode>
</color>
<color>
<red>182</red>
<green>218</green>
<blue>218</blue>
<hexcode>b6dada</hexcode>
</color>
<color>
<red>101</red>
<green>196</green>
<blue>202</blue>
<hexcode>65c4ca</hexcode>
</color>
<color>
<red>43</red>
<green>123</green>
<blue>184</blue>
<hexcode>2b7bb8</hexcode>
</color>
</palette>

=== xjrga/looks/palettes/edgar_degas_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/src/main/resources/palette.xsd">
    <name>L Etoile by Edgar Degas</name>
    <color>
        <red>122</red>
        <green>101</green>
        <blue>78</blue>
        <hexcode>7a654e</hexcode>
    </color>
    <color>
        <red>233</red>
        <green>203</green>
        <blue>183</blue>
        <hexcode>e9cbb7</hexcode>
    </color>
    <color>
        <red>172</red>
        <green>113</green>
        <blue>59</blue>
        <hexcode>ac713b</hexcode>
    </color>
    <color>
        <red>120</red>
        <green>129</green>
        <blue>141</blue>
        <hexcode>78818d</hexcode>
    </color>
    <color>
        <red>53</red>
        <green>46</green>
        <blue>35</blue>
        <hexcode>352e23</hexcode>
    </color>
</palette>

=== xjrga/looks/palettes/van_gogh_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/src/main/resources/palette.xsd">
<name>Van Gogh’s “The Painter on the Road to Tarascon” (1888)</name>
<color>
<red>92</red>
<green>140</green>
<blue>78</blue>
<hexcode>5c8c4e</hexcode>
</color>
<color>
<red>135</red>
<green>188</green>
<blue>146</blue>
<hexcode>87bc92</hexcode>
</color>
<color>
<red>220</red>
<green>173</green>
<blue>59</blue>
<hexcode>dcad3b</hexcode>
</color>
<color>
<red>46</red>
<green>136</green>
<blue>170</blue>
<hexcode>2e88aa</hexcode>
</color>
<color>
<red>61</red>
<green>67</green>
<blue>53</blue>
<hexcode>3d4335</hexcode>
</color>
</palette>

=== xjrga/looks/palettes/raphael_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="https://raw.githubusercontent.com/x-jrga/schemas/main/palette.xsd">
    <name>Saint Catherine of Alexandria by Raphael</name>
    <color>
        <red>252</red>
        <green>229</green>
        <blue>189</blue>
        <hexcode>fce5bd</hexcode>
    </color>
    <color>
        <red>107</red>
        <green>81</green>
        <blue>46</blue>
        <hexcode>6b512e</hexcode>
    </color>
    <color>
        <red>191</red>
        <green>51</green>
        <blue>34</blue>
        <hexcode>bf3322</hexcode>
    </color>
    <color>
        <red>101</red>
        <green>101</green>
        <blue>129</blue>
        <hexcode>656581</hexcode>
    </color>
    <color>
        <red>230</red>
        <green>164</green>
        <blue>90</blue>
        <hexcode>e6a45a</hexcode>
    </color>
</palette>

=== xjrga/looks/palettes/van_gogh_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/src/main/resources/palette.xsd">
    <name>Van Gogh’s “Wheatfield with Crows” (1890)</name>
    <color>
        <red>1</red>
        <green>56</green>
        <blue>86</blue>
        <hexcode>13856</hexcode>
    </color>
    <color>
        <red>57</red>
        <green>126</green>
        <blue>191</blue>
        <hexcode>397ebf</hexcode>
    </color>
    <color>
        <red>116</red>
        <green>56</green>
        <blue>55</blue>
        <hexcode>743837</hexcode>
    </color>
    <color>
        <red>236</red>
        <green>198</green>
        <blue>75</blue>
        <hexcode>ecc64b</hexcode>
    </color>
    <color>
        <red>96</red>
        <green>122</green>
        <blue>77</blue>
        <hexcode>607a4d</hexcode>
    </color>
</palette>

=== xjrga/looks/palettes/edvard_munch_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/palette.xsd">
<name>The Scream by Edvard Munch</name>
<color>
<red>208</red>
<green>64</green>
<blue>10</blue>
<hexcode>d0400a</hexcode>
</color>
<color>
<red>30</red>
<green>53</green>
<blue>57</blue>
<hexcode>1e3539</hexcode>
</color>
<color>
<red>126</red>
<green>113</green>
<blue>75</blue>
<hexcode>7e714b</hexcode>
</color>
<color>
<red>184</red>
<green>162</green>
<blue>96</blue>
<hexcode>b8a260</hexcode>
</color>
<color>
<red>219</red>
<green>119</green>
<blue>16</blue>
<hexcode>db7710</hexcode>
</color>
</palette>

=== xjrga/looks/palettes/van_gogh_04.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="palette.xsd">
    <name>Starry Night by Vincent van Gogh</name>
    <color>
        <red>6</red>
        <green>12</green>
        <blue>15</blue>
        <hexcode>60c0f</hexcode>
    </color>
    <color>
        <red>29</red>
        <green>88</green>
        <blue>128</blue>
        <hexcode>1d5880</hexcode>
    </color>
    <color>
        <red>254</red>
        <green>206</green>
        <blue>62</blue>
        <hexcode>fece3e</hexcode>
    </color>
    <color>
        <red>248</red>
        <green>226</green>
        <blue>136</blue>
        <hexcode>f8e288</hexcode>
    </color>
    <color>
        <red>159</red>
        <green>199</green>
        <blue>152</blue>
        <hexcode>9fc798</hexcode>
    </color>
</palette>

=== xjrga/looks/palettes/leonardo_da_vinci_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/src/main/resources/palette.xsd">
    <name>Mona Lisa by Leonardo da Vinci</name>
    <color>
        <red>172</red>
        <green>92</green>
        <blue>44</blue>
        <hexcode>ac5c2c</hexcode>
    </color>
    <color>
        <red>200</red>
        <green>163</green>
        <blue>83</blue>
        <hexcode>c8a353</hexcode>
    </color>
    <color>
        <red>40</red>
        <green>25</green>
        <blue>36</blue>
        <hexcode>281924</hexcode>
    </color>
    <color>
        <red>137</red>
        <green>120</green>
        <blue>70</blue>
        <hexcode>897846</hexcode>
    </color>
    <color>
        <red>155</red>
        <green>160</green>
        <blue>104</blue>
        <hexcode>9ba068</hexcode>
    </color>
    <color>
        <red>224</red>
        <green>213</green>
        <blue>193</blue>
        <hexcode>e0d5c1</hexcode>
    </color>
</palette>
