=== xjrga/looks/src/main/resources/palette.xsd
<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="palette">
        <xsd:annotation>
            <xsd:documentation>
                Data Exchange Document Schema For Palette Viewer Software
                Palette Viewer: Software to Create Color Palettes.
                Author: Jorge Garcia R de Alba
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="color" type="color_type" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="Uniquely_Specified_Color">
            <xsd:selector xpath="color"/>
            <xsd:field xpath="red"/>
            <xsd:field xpath="green"/>
            <xsd:field xpath="blue"/>
        </xsd:unique>
    </xsd:element>
    <!-- Color -->
    <xsd:complexType name="color_type">
        <xsd:sequence>
            <xsd:element name="hexcode" type="hex_color_code_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="red" type="red_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="green" type="green_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="blue" type="blue_type" minOccurs="1" maxOccurs="1"/>            
        </xsd:sequence>
    </xsd:complexType>
    <!-- Hex Color Code -->
    <xsd:simpleType name="hex_color_code_type">
        <xsd:restriction base="xsd:hexBinary">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Red -->
    <xsd:simpleType name="red_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Green -->
    <xsd:simpleType name="green_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Blue -->
    <xsd:simpleType name="blue_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== xjrga/looks/palettes/hokusai_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="palette.xsd">
<name>Great Wave Off Kanagawa (Kanagawa Oki Nami Ura) by Hokusai</name>
<color>
<red>125</red>
<green>155</green>
<blue>166</blue>
<hexcode>7d9ba6</hexcode>
</color>
<color>
<red>192</red>
<green>183</green>
<blue>168</blue>
<hexcode>c0b7a8</hexcode>
</color>
<color>
<red>221</red>
<green>211</green>
<blue>196</blue>
<hexcode>ddd3c4</hexcode>
</color>
<color>
<red>16</red>
<green>40</green>
<blue>74</blue>
<hexcode>10284a</hexcode>
</color>
<color>
<red>71</red>
<green>75</green>
<blue>78</blue>
<hexcode>474b4e</hexcode>
</color>
</palette>
