=== xjrga/looks/src/main/resources/palette.xsd
<xsd:schema version="1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="palette">
        <xsd:annotation>
            <xsd:documentation>
                Data Exchange Document Schema For Palette Viewer Software
                Palette Viewer: Software to Create Color Palettes.
                Author: Jorge Garcia R de Alba
            </xsd:documentation>
        </xsd:annotation>
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="name" type="xsd:string" minOccurs="1" maxOccurs="1"/>
                <xsd:element name="color" type="color_type" minOccurs="1" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
        <xsd:unique name="Uniquely_Specified_Color">
            <xsd:selector xpath="color"/>
            <xsd:field xpath="red"/>
            <xsd:field xpath="green"/>
            <xsd:field xpath="blue"/>
        </xsd:unique>
    </xsd:element>
    <!-- Color -->
    <xsd:complexType name="color_type">
        <xsd:sequence>
            <xsd:element name="hexcode" type="hex_color_code_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="red" type="red_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="green" type="green_type" minOccurs="1" maxOccurs="1"/>
            <xsd:element name="blue" type="blue_type" minOccurs="1" maxOccurs="1"/>            
        </xsd:sequence>
    </xsd:complexType>
    <!-- Hex Color Code -->
    <xsd:simpleType name="hex_color_code_type">
        <xsd:restriction base="xsd:hexBinary">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Red -->
    <xsd:simpleType name="red_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Green -->
    <xsd:simpleType name="green_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
    <!-- Blue -->
    <xsd:simpleType name="blue_type">
        <xsd:restriction base="xsd:nonNegativeInteger">
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== xjrga/looks/palettes/johannes_vermeer_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/src/main/resources/palette.xsd">
    <name>Girl with a Pearl Earring by Johannes Vermeer</name>
    <color>
        <red>18</red>
        <green>10</green>
        <blue>19</blue>
        <hexcode>120a13</hexcode>
    </color>
    <color>
        <red>72</red>
        <green>93</green>
        <blue>165</blue>
        <hexcode>485da5</hexcode>
    </color>
    <color>
        <red>205</red>
        <green>182</green>
        <blue>122</blue>
        <hexcode>cdb67a</hexcode>
    </color>
    <color>
        <red>137</red>
        <green>97</green>
        <blue>53</blue>
        <hexcode>896135</hexcode>
    </color>
    <color>
        <red>112</red>
        <green>40</green>
        <blue>33</blue>
        <hexcode>702821</hexcode>
    </color>
</palette>

=== xjrga/looks/palettes/van_gogh_03.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/palette.xsd">
<name>Van Gogh’s “Café Terrace on the Place du Forum, Arles” (1888)</name>
<color>
<red>40</red>
<green>85</green>
<blue>176</blue>
<hexcode>2855b0</hexcode>
</color>
<color>
<red>103</red>
<green>149</green>
<blue>209</blue>
<hexcode>6795d1</hexcode>
</color>
<color>
<red>229</red>
<green>153</green>
<blue>59</blue>
<hexcode>e5993b</hexcode>
</color>
<color>
<red>249</red>
<green>223</green>
<blue>86</blue>
<hexcode>f9df56</hexcode>
</color>
<color>
<red>30</red>
<green>44</green>
<blue>53</blue>
<hexcode>1e2c35</hexcode>
</color>
</palette>

=== xjrga/looks/palettes/luis_barragan.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/src/main/resources/palette.xsd">
    <name>Luis Barragan</name>
    <color>
        <red>187</red>
        <green>45</green>
        <blue>129</blue>
        <hexcode>bb2d81</hexcode>
    </color>
    <color>
        <red>219</red>
        <green>80</green>
        <blue>39</blue>
        <hexcode>db5027</hexcode>
    </color>
    <color>
        <red>231</red>
        <green>186</green>
        <blue>23</blue>
        <hexcode>e7ba17</hexcode>
    </color>
    <color>
        <red>176</red>
        <green>21</green>
        <blue>16</blue>
        <hexcode>b01510</hexcode>
    </color>
    <color>
        <red>44</red>
        <green>170</green>
        <blue>255</blue>
        <hexcode>2caaff</hexcode>
    </color>
</palette>

=== xjrga/looks/palettes/frida_kahlo_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/src/main/resources/palette.xsd">
    <name>Self-Portrait with Thorn Necklace and Hummingbird, c.1940 By Frida Kahlo</name>
    <color>
        <red>238</red>
        <green>207</green>
        <blue>94</blue>
        <hexcode>eecf5e</hexcode>
    </color>
    <color>
        <red>228</red>
        <green>171</green>
        <blue>69</blue>
        <hexcode>e4ab45</hexcode>
    </color>
    <color>
        <red>151</red>
        <green>169</green>
        <blue>151</blue>
        <hexcode>97a997</hexcode>
    </color>
    <color>
        <red>100</red>
        <green>120</green>
        <blue>10</blue>
        <hexcode>64780a</hexcode>
    </color>
    <color>
        <red>35</red>
        <green>65</green>
        <blue>16</blue>
        <hexcode>234110</hexcode>
    </color>
    <color>
        <red>189</red>
        <green>65</green>
        <blue>28</blue>
        <hexcode>bd411c</hexcode>
    </color>
</palette>

=== xjrga/looks/palettes/gustav_klimt.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="file:/home/jr/Project/Queued/Looks/src/main/resources/palette.xsd">
<name>The Kiss by Gustav Klimt</name>
<color>
<red>125</red>
<green>106</green>
<blue>60</blue>
<hexcode>7d6a3c</hexcode>
</color>
<color>
<red>199</red>
<green>169</green>
<blue>77</blue>
<hexcode>c7a94d</hexcode>
</color>
<color>
<red>119</red>
<green>143</green>
<blue>80</blue>
<hexcode>778f50</hexcode>
</color>
<color>
<red>142</red>
<green>117</green>
<blue>128</blue>
<hexcode>8e7580</hexcode>
</color>
<color>
<red>182</red>
<green>100</green>
<blue>78</blue>
<hexcode>b6644e</hexcode>
</color>
</palette>

=== xjrga/looks/palettes/edward_hopper_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="palette.xsd">
    <name>Nighthawks by Edward Hopper</name>
    <color>
        <red>119</red>
        <green>52</green>
        <blue>30</blue>
        <hexcode>77341e</hexcode>
    </color>
    <color>
        <red>235</red>
        <green>227</green>
        <blue>135</blue>
        <hexcode>ebe387</hexcode>
    </color>
    <color>
        <red>98</red>
        <green>142</green>
        <blue>113</blue>
        <hexcode>628e71</hexcode>
    </color>
    <color>
        <red>21</red>
        <green>43</green>
        <blue>54</blue>
        <hexcode>152b36</hexcode>
    </color>
    <color>
        <red>33</red>
        <green>40</green>
        <blue>37</blue>
        <hexcode>212825</hexcode>
    </color>
</palette>

=== xjrga/looks/palettes/rembrandt_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="palette.xsd">
    <name>The Nightwatch by Rembrandt</name>
    <color>
        <red>10</red>
        <green>13</green>
        <blue>12</blue>
        <hexcode>0a0d0c</hexcode>
    </color>
    <color>
        <red>245</red>
        <green>220</green>
        <blue>150</blue>
        <hexcode>f5dc96</hexcode>
    </color>
    <color>
        <red>129</red>
        <green>38</green>
        <blue>15</blue>
        <hexcode>81260f</hexcode>
    </color>
    <color>
        <red>36</red>
        <green>28</green>
        <blue>15</blue>
        <hexcode>241c0f</hexcode>
    </color>
    <color>
        <red>42</red>
        <green>44</green>
        <blue>40</blue>
        <hexcode>2a2c28</hexcode>
    </color>
</palette>

=== xjrga/looks/palettes/tinkerbell.xml
<?xml version="1.0" encoding="UTF-8"?>
<palette xmlns:xsd="http://www.w3.org/2001/XMLSchema-instance" xsd:noNamespaceSchemaLocation="palette.xsd">
<name>Tinkerbell</name>
<color>
<red>201</red>
<green>115</green>
<blue>102</blue>
<hexcode>c97366</hexcode>
</color>
<color>
<red>186</red>
<green>117</green>
<blue>145</blue>
<hexcode>ba7591</hexcode>
</color>
<color>
<red>168</red>
<green>187</green>
<blue>121</blue>
<hexcode>a8bb79</hexcode>
</color>
<color>
<red>95</red>
<green>124</green>
<blue>81</blue>
<hexcode>5f7c51</hexcode>
</color>
<color>
<red>112</red>
<green>143</green>
<blue>158</blue>
<hexcode>708f9e</hexcode>
</color>
<color>
<red>205</red>
<green>101</green>
<blue>78</blue>
<hexcode>cd654e</hexcode>
</color>
<color>
<red>223</red>
<green>220</green>
<blue>216</blue>
<hexcode>dfdcd8</hexcode>
</color>
<color>
<red>194</red>
<green>164</green>
<blue>106</blue>
<hexcode>c2a46a</hexcode>
</color>
<color>
<red>179</red>
<green>141</green>
<blue>110</blue>
<hexcode>b38d6e</hexcode>
</color>
<color>
<red>198</red>
<green>107</green>
<blue>109</blue>
<hexcode>c66b6d</hexcode>
</color>
<color>
<red>215</red>
<green>142</green>
<blue>81</blue>
<hexcode>d78e51</hexcode>
</color>
<color>
<red>58</red>
<green>58</green>
<blue>59</blue>
<hexcode>3a3a3b</hexcode>
</color>
<color>
<red>131</red>
<green>163</green>
<blue>180</blue>
<hexcode>83a3b4</hexcode>
</color>
<color>
<red>173</red>
<green>124</green>
<blue>92</blue>
<hexcode>ad7c5c</hexcode>
</color>
</palette>
